### ISSUE TITLE
For statement

### ISSUE THREAD

**Issue by GnusinPavel** [dattran92/simplequeue#1]
https://github.com/dattran92/simplequeue/blob/29f60991ebccc464a4bf081235a3ecf0f0b9fbce/queue/queue.go#L17

Hi! Can you explain why did you use "for" statement here? Thx!

**Comment by dattran92** [comment]
`Queue.lock` fails when another is locking this queue. That's why we need a `for` to keep trying until the queue is released so that it can lock and run the statement.

**Comment by GnusinPavel** [comment]
Accordantly to the Mutex documentation
`Lock locks m. If the lock is already in use, the calling goroutine blocks until the mutex is available.`
So it blocks a goroutine but not fails. What is the version of go?

**Comment by GnusinPavel** [comment]
And what does it mean "fails"? Can you describe how it would be works when fails? Sorry for my noisy, but it's really interesting for me )
